apiVersion: v1
kind: Pod
metadata:
  name: pod-certificates-example
  namespace: default
  annotations:
    k8s-135.podinit.sh/pcs-cn: "my-pod.com"
    k8s-135.podinit.sh/pcs-san: "identity.my-pod.com"
    k8s-135.podinit.sh/pcs-duration: "1h"
    k8s-135.podinit.sh/pcs-refresh: "30m"
spec:
  terminationGracePeriodSeconds: 1
  automountServiceAccountToken: false
  containers:
    - name: main
      image: alpine/openssl:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: mtls-credentials
          mountPath: /run/credentials
  volumes:
    - name: mtls-credentials
      projected:
        sources:
          - podCertificate:
              signerName: "k8s-135.podinit.sh/pcs"
              keyType: ED25519
              credentialBundlePath: credentialbundle.pem
